id: I5A641644
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:06:36+00:00'
last_modified: '2022-06-07T12:21:59.439204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20144
  title: ཡེ་ཤེས་བླ་མའི་སྙིང་ཐིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    52BC:
      image_group_id: I8LS20146
      title: Volume 1 of ye shes bla ma'i snying thig
      total_pages: 190
      order: 1
      base_file: 52BC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
