id: P000576
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20144
  title: ཡེ་ཤེས་བླ་མའི་སྙིང་ཐིག
  author: ''
  volumes:
    8448190c7dab427ab7c89e018c5dea8f:
      image_group_id: I8LS20146
      title: Volume 1 of ye shes bla ma'i snying thig
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
